title: AI-Body Problem
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Unease about artificial intelligence is often expressed in terms of the effects of bias, or job displacement, or singularity (the fear that AI will take over). Our thesis is that a major source of uneasiness, one which has not been much explored, is AI’s uncanniness.
#baseurl: "/aar-presentation-2019-dev"
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username:
#github_username:

repository: "nicolas-van/bootstrap-4-github-pages"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - index.md
  - argument.md
  - topic-model.md
  - gpt2.md
  - conclusion.md
  - bibliography.md


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
